# Generated by Django 3.0.2 on 2020-02-13 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('mobile', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('shift', models.CharField(choices=[('D', 'Day'), ('N', 'Night'), ('LN', 'Late Night')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(unique=True)),
                ('age', models.SmallIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('sickness', models.CharField(default='', max_length=30, null=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Nurse')),
            ],
        ),
        migrations.CreateModel(
            name='Bed_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sickness', models.CharField(max_length=30)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Nurse')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('bedsore', models.ImageField(upload_to='')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Nurse')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='models.Person')),
            ],
        ),
    ]
