# Generated by Django 3.0.2 on 2020-02-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bedsore',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
