# Generated by Django 3.0.2 on 2020-02-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20200213_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bedsore',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
