# Generated by Django 3.0.2 on 2020-02-15 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_auto_20200213_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed_history',
            name='bed',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='models.Bed'),
        ),
    ]
