# Generated by Django 3.0.2 on 2020-02-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20200216_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='bedsore',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
