# Generated by Django 3.0.2 on 2020-02-16 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_auto_20200216_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='person',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nurse',
        ),
        migrations.AddField(
            model_name='person',
            name='bed',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='models.Bed'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='bedsore',
            field=models.ImageField(blank=True, null=True, upload_to='bedsores'),
        ),
        migrations.AlterField(
            model_name='bed',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.Nurse'),
        ),
        migrations.AlterField(
            model_name='bed_history',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.Nurse'),
        ),
        migrations.AlterField(
            model_name='bed_history',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='models.Person'),
        ),
    ]
